### ISSUE TITLE
Typo in flow_ssl/data/toy_datasets.py

### ISSUE THREAD

**Issue by Warvito** [PolinaKirichenko/flows_ood#2]
There is a typo in [https://github.com/PolinaKirichenko/flows_ood/blob/670271f4f4868fa4ffded9974cc670dcf0da8f97/flow_ssl/data/toy_datasets.py#L54](https://github.com/PolinaKirichenko/flows_ood/blob/670271f4f4868fa4ffded9974cc670dcf0da8f97/flow_ssl/data/toy_datasets.py#L54)

It is missing the # in the beginning of the line

**Comment by PolinaKirichenko** [comment]
Thanks for catching!
